/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/cors/proxy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Proxy */
        post: operations["proxy_cors_proxy_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/litellm/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Litellm Proxy
         * @description Proxy endpoint for LiteLLM API requests with streaming support.
         *     This endpoint forwards all requests to the LiteLLM API service.
         */
        get: operations["litellm_proxy_litellm__path__get"];
        /**
         * Litellm Proxy
         * @description Proxy endpoint for LiteLLM API requests with streaming support.
         *     This endpoint forwards all requests to the LiteLLM API service.
         */
        put: operations["litellm_proxy_litellm__path__put"];
        /**
         * Litellm Proxy
         * @description Proxy endpoint for LiteLLM API requests with streaming support.
         *     This endpoint forwards all requests to the LiteLLM API service.
         */
        post: operations["litellm_proxy_litellm__path__post"];
        /**
         * Litellm Proxy
         * @description Proxy endpoint for LiteLLM API requests with streaming support.
         *     This endpoint forwards all requests to the LiteLLM API service.
         */
        delete: operations["litellm_proxy_litellm__path__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/doc-parse/parse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Parse Document */
        post: operations["parse_document_doc_parse_parse_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/searxng": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Searxng */
        get: operations["searxng_searxng_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Check API and database health
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/process": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Process Input
         * @description Process natural language input and extract relationships
         *
         *     - **user_id**: Required GUID for tracking data ownership
         *     - **descriptions**: List of natural language texts to process
         *     - **metadata**: Optional additional metadata
         */
        post: operations["process_input_process_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search Knowledge Graph
         * @description Search the knowledge graph using natural language
         *
         *     - **query**: Natural language search query
         *     - **search_type**: Type of search (graph/vector/both)
         *     - **user_id**: Optional filter by user ID
         *     - **k**: Number of results to return
         */
        post: operations["search_knowledge_graph_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/node-relations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get Node Relations
         * @description Get all relations for a specific node by name
         *
         *     - **node_name**: Name of the node to search relations for
         *     - **source**: Optional filter by source metadata
         *     - **user_id**: Optional filter by user ID
         */
        post: operations["get_node_relations_node_relations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Statistics
         * @description Get system statistics, optionally filtered by user
         */
        get: operations["get_statistics_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_parse_document_doc_parse_parse_post */
        Body_parse_document_doc_parse_parse_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
            /**
             * Language
             * @default en
             */
            language: string | null;
            /** Target Pages */
            target_pages?: string | null;
        };
        /**
         * EdgeResult
         * @description Individual edge processing result
         */
        EdgeResult: {
            /** Action */
            action: string;
            /** Message */
            message?: string | null;
            /** Input Description */
            input_description: string;
            /** Extracted Info */
            extracted_info?: {
                [key: string]: unknown;
            } | null;
            /** Count */
            count?: number | null;
            /** Conflicts Resolved */
            conflicts_resolved?: number | null;
            /** Obsoleted Relationships */
            obsoleted_relationships?: string[] | null;
            /** Search Info */
            search_info?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Health check response
         */
        HealthResponse: {
            /** Status */
            status: string;
            /** Neo4J Connected */
            neo4j_connected: boolean;
            /** Engine Initialized */
            engine_initialized: boolean;
            /** Version */
            version: string;
        };
        /**
         * NodeRelationsRequest
         * @description Request model for searching all relations of a node
         */
        NodeRelationsRequest: {
            /**
             * Node Name
             * @description Name of the node to search relations for
             */
            node_name: string;
            /**
             * Source
             * @description Optional: Filter relations by source metadata
             */
            source?: string | null;
            /**
             * User Id
             * @description Optional: Filter results by user ID
             */
            user_id?: string | null;
            /**
             * Filter Obsolete
             * @description Whether to filter out obsolete relations
             * @default true
             */
            filter_obsolete: boolean | null;
        };
        /**
         * NodeRelationsResponse
         * @description Response model for node relations
         */
        NodeRelationsResponse: {
            /** Node Name */
            node_name: string;
            /** Relations */
            relations: components["schemas"]["SearchResult"][];
            /** Total Relations */
            total_relations: number;
            /** Processing Time Ms */
            processing_time_ms: number;
        };
        /**
         * ProcessInputRequest
         * @description Request model for processing natural language input
         */
        ProcessInputRequest: {
            /**
             * User Id
             * Format: uuid
             * @description User ID (GUID) for tracking ownership
             */
            user_id: string;
            /**
             * Descriptions
             * @description List of natural language descriptions to process
             */
            descriptions: string[];
            /**
             * Metadata
             * @description Additional metadata
             */
            metadata?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * ProcessInputResponse
         * @description Response model for input processing
         */
        ProcessInputResponse: {
            /** Status */
            status: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Processed Items */
            processed_items: number;
            /** New Edges */
            new_edges: number;
            /** Updated Edges */
            updated_edges: number;
            /** Obsoleted Edges */
            obsoleted_edges: number;
            /** Duplicates Ignored */
            duplicates_ignored: number;
            /** Processing Time Ms */
            processing_time_ms: number;
            /** Errors */
            errors?: string[];
            /** Edge Results */
            edge_results?: components["schemas"]["EdgeResult"][];
        };
        /** ProxyRequest */
        ProxyRequest: {
            /** Method */
            method: string;
            /** Url */
            url: string;
            /** Headers */
            headers?: {
                [key: string]: string;
            } | null;
            /** Body */
            body?: unknown | null;
        };
        /**
         * SearchRequest
         * @description Request model for searching the knowledge graph
         */
        SearchRequest: {
            /**
             * Query
             * @description Natural language search query
             */
            query: string;
            /**
             * Search Type
             * @description Type of search to perform
             * @default both
             * @enum {string}
             */
            search_type: "graph" | "vector" | "both";
            /**
             * User Id
             * @description Optional: Filter results by user ID
             */
            user_id?: string | null;
            /**
             * K
             * @description Number of results to return
             * @default 10
             */
            k: number;
        };
        /**
         * SearchResponse
         * @description Response model for search queries
         */
        SearchResponse: {
            /** Query */
            query: string;
            /** Search Type */
            search_type: string;
            /** Answer */
            answer: string | null;
            /** Results */
            results: components["schemas"]["SearchResult"][];
            /** Total Results */
            total_results: number;
            /** Processing Time Ms */
            processing_time_ms: number;
            /** User Filter Applied */
            user_filter_applied: boolean;
        };
        /**
         * SearchResult
         * @description Individual search result
         */
        SearchResult: {
            /** Subject */
            subject: string;
            /** Relationship */
            relationship: string;
            /** Object */
            object: string;
            /** Confidence */
            confidence: number;
            /** User Id */
            user_id: string | null;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    proxy_cors_proxy_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProxyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    litellm_proxy_litellm__path__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    litellm_proxy_litellm__path__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    litellm_proxy_litellm__path__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    litellm_proxy_litellm__path__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    parse_document_doc_parse_parse_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_parse_document_doc_parse_parse_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    searxng_searxng_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    process_input_process_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProcessInputRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProcessInputResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_knowledge_graph_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_node_relations_node_relations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NodeRelationsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeRelationsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_statistics_stats_get: {
        parameters: {
            query?: {
                /** @description Filter stats by user ID */
                user_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
