// This file is being kept for backward compatibility during the refactoring process.
// It re-exports the utils from its new location in the shared module.
// TODO: Update all imports to reference @shared/utils/functions directly and remove this file.

export {
  randomHash,
  escapeRegex,
  escapeHtml,
  defaultAvatar,
  hctToHex,
  genId,
  idTimestamp,
  idDateString,
  JSONEqual,
  mimeTypeMatch,
  isTextFile,
  wrapCode,
  wrapQuote,
  parseSeconds,
  caselessIncludes,
  displayLength,
  parsePageRange,
  pageFhStyle,
  almostEqual,
  isPlatformEnabled,
  textBeginning,
  getFileExt,
  saveArtifactChanges,
  restoreArtifactChanges,
  blobToBase64,
  base64ToArrayBuffer,
  artifactUnsaved,
  removeUndefinedProps,
  cyrb53,
  hash53,
  removeDuplicates,
  localePrice,
  defaultTextAvatar,
  avatarKey,
} from "@shared/utils/functions"
