name: Docker Image CI

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create .env.docker
        run: |
          echo "DEXIE_DB_URL=${{ secrets.DEXIE_DB_URL }}" >> .env.docker
          echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> .env.docker
          echo "SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}" >> .env.docker

      - name: Build and push
        uses: docker/build-push-action@v6.10.0
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/aiaw:dev
